### PR TITLE
Use authentication when hitting the Github API.

### PR DESCRIPTION
**Pull request by freakboy3742**
We've started hitting the API rate limit when querying the Github API. e.g.,

https://github.com/beeware/briefcase-web-static-template/actions/runs/4273741637/jobs/7496132787

We should be able to get a vastly increased rate limit by using authenticated API access.

## PR Checklist:

- [x] All new features have been tested
- [x] All new features have been documented
- [x] I have read the **CONTRIBUTING.md** file
- [x] I will abide by the code of conduct

### CODE REVIEW

**Comment by rmartin16** [comment]
This'll probably require `secrets: inherit` everywhere these actions/workflows are used....that's my guess anyway for the failures

**Comment by freakboy3742** [comment]
This will also need an update to all the template repos to pass in a token with read permissions; plus an update to briefcase repo with the same.

**Review by rmartin16 — COMMENTED** [review]
I implemented a slightly different approach in #19. Let me know what you think.

**Comment by freakboy3742** [comment]
Yours is better :-)

**Pull request closed without merging**
