### PR TITLE
Run Linux apps from Docker

### PR DESCRIPTION
**Pull request by rmartin16**
- See https://github.com/beeware/briefcase/pull/1603 for new requirements

## PR Checklist:

- [x] All new features have been tested
- [x] All new features have been documented
- [X] I have read the **CONTRIBUTING.md** file
- [X] I will abide by the code of conduct

### CODE REVIEW

**Comment by rmartin16** [comment]
This shouldn't be merged until beeware/briefcase#1603 is ready to be merged.
- The `Install Briefcase` failures are because `Briefcase-Repo` is declared
- The `Verify Briefcase` failures are because it's using Briefcase v0.3.17

**Comment by rmartin16** [comment]
FYI....when you use `Briefcase-Repo` with a fork....be sure the git tags in the fork are up-to-date....otherwise, the wrong project/app templates are probably gonna be [used](https://github.com/beeware/.github/actions/runs/7807535121/job/21296884507#step:18:37)...

**Comment by rmartin16** [comment]
Removing `SDL_VIDEODRIVER=dummy` has revealed some subtle difference among the GitHub macOS runners that causes `briefcase run` for Pygame to sometimes [fail](https://github.com/beeware/.github/actions/runs/7823794704/job/21345368618#step:14:127) with `No hardware accelerated renderers available`.

From the information available, I can't detect meaningful differences in the runner between success and failure...but given the error is about missing hardware renders, it could just be the underlying hardware....especially if GitHub isn't actually running macOS runners in virtualization.

**Review by freakboy3742 — APPROVED** [review]
This all looks good, and it passes CI; I won't merge because it's still marked Draft, but if you've got nothing else to add, feel free to mark final and merge.

**Pull request merged**
