### PR TITLE
 Perform Linux package installs as dry runs 

### PR DESCRIPTION
**Pull request by rmartin16**
Trying to cut down time spent in CI for build apps for Linux.

## PR Checklist:

- [X] All new features have been tested
- [X] All new features have been documented
- [X] I have read the **CONTRIBUTING.md** file
- [X] I will abide by the code of conduct

### CODE REVIEW

**Comment by rmartin16** [comment]
### Before:
image

### After:
image

sooo, not especially striking...but something, I suppose.

**Review by freakboy3742 — COMMENTED** [review]
I'm all up for faster CI... but is this really a good idea? A dry run may be faster, but that's because it's *not* doing the thing that we're trying to validate works.

**Comment by rmartin16** [comment]
> I'm all up for faster CI... but is this really a good idea? A dry run may be faster, but that's because it's _not_ doing the thing that we're trying to validate works.

Well, yes and no, I suppose.

The part I really wanted to test by actually installing the produced package was ensuring:
- the package could be properly read by package manager
- the dependencies listed therein are valid according to the package manager

AFAICT, these two steps still happen for a dry run....it just doesn't waste all the additional time of downloading and unpacking those dependencies....which Briefcase really has no bearing on anyway.

**Review by freakboy3742 — APPROVED** [review]
That's fair. I guess my concern is that the unpacking process might reveal that a file can't be unpacked, or something like that - but that's probably enough of an edge case that it's not worth worrying about.

**Pull request merged**
